source 'https://github.com/CocoaPods/Specs.git'

target 'HaidoraProgressHUDManager_Example', :exclusive => true do
  pod "HaidoraProgressHUDManager", :path => "../"
end

target 'HaidoraProgressHUDManager_Tests', :exclusive => true do
  pod "HaidoraProgressHUDManager", :path => "../"

  
end
